BEGIN TRANSACTION;
CREATE TABLE "Gold" (
	`id`	INTEGER,
	`Character`	TEXT,
	`Name`	TEXT,
	`Radicals`	TEXT,
	`Japanese_Name`	TEXT,
	`Story`	TEXT,
	`bracket`	INTEGER,
	`easiness`	REAL,
	`next_due_date`	TEXT,
	`prev_due_date`	INTEGER,
	`consecutive_answered`	INTEGER,
	`prev_days_interval`	INTEGER,
	PRIMARY KEY(`id`)
);
INSERT INTO `Gold` VALUES (1,'銭','coin','Gold, Two, Halberd','ぜに',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (2,'皇','emperor','White, King','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (3,'呉','give','Mouth, One, Legs','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (4,'秘','secret','Tree, Invariable','ひ.める',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (5,'酔','drunk','West, Nine, Ten','よ.う',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (6,'捨','discard','Hand, Roof, Soil, Mouth','す.てる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (7,'害','harm','Crown, Soil, Mouth','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (8,'割','proportion','Harm, Sword','さ.く; わ.る; わ.れる; わり',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (9,'柄','design','Tree, Person, Upside down box','え; がら',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (10,'厄','unlucky','Cliff','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (11,'危','dangerous','Wrap, Unlucky','あぶ.ない; あや.うい; あや.ぶむ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (12,'匹','equal','Box on side, Legs','ひき',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (13,'甚','tremendously','Ear, Equal','はなは.だ; はなは.だしい',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (14,'便','convenience','Person, Grow late','たよ.り',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (15,'騒','boisterous','Horse, Right hand, Insect','さわ.ぐ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (16,'聴','listen','Ear, Gentleman, Net, Heart','き.く',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (17,'短','short','Dart, One, Mouth','みじか.い',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (18,'席','seat','Cliff, Towel','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (19,'哲','philosophy','Hand, Ax, Mouth','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (20,'承','acquiesce','Child, Hand','うけたまわ.る',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (21,'遣','dispatch','Road, One, Stick, Mouth','つか.う; つか.わす',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (22,'資','assets','Ice, Lack, Shellfish','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (23,'灯','lamp','Fire, Pin','ひ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (24,'徒','junior','Stop, Run','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (25,'舎','cottage','Roof, Soil, Mouth','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (26,'章','badge','Erect, Day, Ten','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (27,'鏡','mirror','Gold, Erect, Shellfish','かがみ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (28,'就','concerning','Kettle, Reasonable, Mouth','つ.く; つ.ける',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (29,'値','price','Person, Ten, Eye','あたい; ね',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (30,'農','agriculture','Cliff, One, Garment','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (31,'傷','wound','Person, Day, Piggy bank','いた.む; いた.める; きず',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (32,'阿','Africa','Bow, One, Mouth, Pin','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (33,'朱','vermilion','Slash, One, Tree','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (34,'殊','particularly','Death, Vermillion','こと',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (35,'勇','courage','Private, Rice field, Power','いさ.む',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (36,'温','warm','Water, Day, Dish','あたた.か; あたた.かい; あたた.まる; あたた.める',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (37,'妹','younger sister','Woman, Not yet','いもうと',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (38,'般','carrier','Boat, Pike','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (39,'筋','muscle','Bamboo, Flesh, Power','すじ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (40,'領','jurisdiction','Roof, One, Page','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (41,'激','violent','Water, White, Direction, Strike','はげ.しい',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (42,'這','crawl','Road, Say','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (43,'樣','manner','Tree, Sheep, Water','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (44,'曽','formerly','Rice field, Day','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (45,'増','increase','Soil, Formerly','ふ.える; ふ.やす; ま.す',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (46,'迷','astray','Road, Rice','まよ.う',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (47,'技','skill','Hand, Branch','わざ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (48,'頂','place on the head','Pin, Page','いただ.く; いただき',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (49,'昼','daytime','Shaku, Day, One','ひる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (50,'備','equip','Person, Flower, Cliff, Utilize
','そな.える; そな.わる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (51,'霊','spirits','Rain, Two','たま',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (52,'否','negate','One, Slash, Mouth','いな',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (53,'薬','medicine','Flower, White, Tree, Ice','くすり',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (54,'彑','Pig Head','Pig Head','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (55,'互','mutually','One, Pig Head','たが.い',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (56,'隣','neighboring','Bow, Rice, Dancing','とな.る; となり',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (57,'選','elect','Road, Snake, Twenty','えら.ぶ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (58,'跡','tracks','Foot, Kettle, LEgs','あと',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (59,'傾','lean','Change, Page','かたむ.く; かたむ.ける',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (60,'壮','robust','Wand, Gentleman','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (61,'装','attire','Robust, Garment','よそお.う',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (62,'試','test','Say, Halberd, Construction','こころ.みる; ため.す',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (63,'速','quick','Road, Tree, Mouth','すみ.やか; はや.い; はや.める',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (64,'挙','raise','Large, Hand','あ.がる; あ.げる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (65,'層','stratum','Corpse, Rice field, Day','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (66,'芝','turf','Flower','しば',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (67,'詰','packed','Say, Good','つ.まる; つ.む; つ.める',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (68,'量','quantity','Day, Ri','はか.る',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (69,'復','restore','Stop, Day, Strike','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (70,'随','follow','Bow, Road, Scythe, Flesh','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (71,'俗','vulgar','Person, Roof, Mouth','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (72,'奉','dedicate','Two, Large','たてまつ.る',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (73,'浅','shallow','Water, Two, Halberd','あさ.い',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (74,'提','propose','Hand, Day, Head','さ.げる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (75,'浪','wandering','Water, Northeast','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (76,'貧','poverty','Power, Shellfish','まず.しい',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (77,'杯','cupfuls','Tree, Wand','さかずき',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (78,'批','criticism','Hand, Compare','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (79,'紀','chronicle','Thread, Snake','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (80,'吸','suck','Mouth, Reach Out','す.う',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (81,'幕','curtain','Flower, Day, Large, Towel','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (82,'借','borrow','Person, Two, Day','か.りる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (83,'旡','Sob','Sob','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (84,'既','previously','Northeast, Sob','すで.に',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (85,'総','general','Thread, Private, Heart','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (86,'輪','wheel','Car, Roof, Tome','わ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (87,'迎','welcome','Road','むか.える',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (88,'屈','yield','Corpse, Exit','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (89,'脱','undress','Flesh, Legs, Mouth','ぬ.ぐ; ぬ.げる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (90,'尋','inquire','Yo,  Construction, Measurement','たず.ねる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (91,'忠','loyalty','Mouth, Stick, Heart','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (92,'滅','destroy','Water, Cliff, Halberd, Fire','ほろ.びる; ほろ.ぼす',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (93,'荷','baggage','Flower, Person, Mouth, Pin','に',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (94,'遺','bequeath','Road, Mouth, Stick, Shellfish','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (95,'箱','box','Bamboo, Tree, Eye','はこ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (96,'宅','home','Crown','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (97,'叔','uncle','Diviniation, Small, Right hand','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (98,'柳','willow','Tree','やなぎ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (99,'魂','soul','Two, Private, Ghost','たましい',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (100,'埋','bury','Soil, Ri','う.まる; う.める; う.もれる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (101,'依','reliant','Person, Garment','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (102,'帝','sovereign','Erect, Towel','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (103,'捕','catch','Hand, Ten, Flesh','つか.まえる; つか.まる; と.らえる; と.らわれる; と.る',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (104,'級','class','Thread, Reach out','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (105,'秀','excel','Tree, From','ひい.でる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (106,'池','pond','Water, To be','いけ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (107,'植','plant','Tree, Eye','う.える; う.わる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (108,'陰','shade','Bow, Roof, Two, Private','かげ; かげ.る',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (109,'刺','thorn','Tree, Towel, Sword','さ.さる; さ.す',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (110,'伏','prostrated','Person, Dog','ふ.す; ふ.せる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (111,'撃','beat','Car, Pike, King','う.つ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (112,'懸','suspend','Thread, Heart, Eye, Small','か.かる; か.ける',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (113,'触','contact','Angle, Insect','さわ.る; ふ.れる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (114,'伯','chief','Person, White','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (115,'懐','pocket','Wand, Ten, Net, Garment','なつ.かしい; なつ.かしむ; なつ.く; なつ.ける; ふところ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (116,'隅','corner','Bow, Rice Field, Stick, Upside down Box','すみ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (117,'暴','outburst','Day, Water, Well','あば.く; あば.れる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (118,'胃','stomach','Day, Flesh','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (119,'謂','so-called','Say, Stomach','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (120,'珍','rare','King, Roof, Three','めずら.しい',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (121,'区','ward','Side Box, Slash','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (122,'洗','wash','Water, Before','あら.う',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (123,'梅','plum','Tree, Mother','うめ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (124,'智','wisdom','Day, Dart, Mouth','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (125,'迫','urge','Road, White','せま.る',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (126,'健','healthy','Person, Long stride, Brush','すこ.やか',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (127,'惑','beguile','Halberd, Mouth, Heart','まど.う',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (128,'基','fundamentals','Ear, Soil','もと; もとい',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (129,'翌','the following','Feathers, Erect','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (130,'才','genius','One, Feather, Slash','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (131,'称','appellation','Tree, Small','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (132,'膝','knee','Flesh, Tree, Fire','ひざ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (133,'豊','bountiful','Rice Field, Bean','ゆたか',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (134,'崎','promontory','Mountain, Large, Can','さき',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (135,'剣','saber','Roof, Person, Sword','つるぎ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (136,'敢','daring','Ear, Strike','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (137,'厳','stern','Cliff, Daring','おごそ.か; きび.しい',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (138,'納','settlement','Thread, Person, Upside Down Box','おさ.まる; おさ.める',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (139,'展','unfold','Corpse, Garment, Two','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (140,'恥','shame','Ear, Heart','は.じらう; は.じる; は.ずかしい; はじ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (141,'棒','rod','Tree, Large, Two, Stick','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (142,'額','forehead','Crown, Late, Mouth, Page','ひたい',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (143,'伴','consort','Person, Ten, One','ともな.う',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (144,'逆','inverted','One, Mountain, Road','さか; さか.らう',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (145,'閉','closed','Gates, One, Feather, Slash','し.まる; し.める; と.ざす; と.じる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (146,'射','shoot','Somebody, Measurement','い.る',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (147,'憶','recollection','Wand, Erect, Day, Heart','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (148,'瞬','wink','Eye, Day','またた.く',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (149,'威','intimidate','Halberd, Woman','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (150,'哀','pathetic','Kettle, Garment, Mouth','あわ.れ; あわ.れむ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (151,'堪','withstand','Soil, Ear, Legs','た.える',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (152,'殆','almost','Death, Private, Mouth','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (153,'寂','loneliness','Divining, Small, Kettle, Or Again','さび; さび.しい; さび.れる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (154,'被','incur','Clothes, Pelt','こうむ.る',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (155,'斎','purification','Sentence, Two, Small','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (156,'趣','gist','Run, Earth, Or again','おもむき',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (157,'却','instead','Seal, Soil, Private','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (158,'脚','shins','Flesh, Instead','あし',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (159,'講','lecture','Say, Flesh, Ten ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (160,'握','grip','Hand, Corpse, Climax','にぎ.る',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (161,'姓','surname','Woman, Life','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (162,'疲','tired','Cliff, Pelt','つか.らす; つか.れる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (163,'染','dye','Water, Nine, Tree','し.み; し.みる; そ.まる; そ.める',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (164,'斬','chop off','Car, Ax','き.る',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (165,'暫','temporarily','Chop off, Day','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (166,'犯','crime','Dog, Seal','おか.す',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (167,'辞','resign','Tongue, Spicy','や.める',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (168,'砂','sand','Stone, Small','すな',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (169,'牙','tusk','tusk','きば',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (170,'邪','wicked','Tusk, Bow','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (171,'油','oil','Water, Rice field','あぶら',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (172,'闇','pitch dark','Gates, Erect, Day','やみ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (173,'概','outline','Soil, Northeast, Tusk','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (174,'遂','consummate','Road, One, Pig','と.げる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (175,'聖','holy','Ear, Mouth, King','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (176,'汽','vapor','Water, Spirit','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (177,'順','obey','Sword, Page','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (178,'憎','hate','Wand, Rice Field, Day','にく.い; にく.しみ; にく.む; にく.らしい',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (179,'益','benefit','Large, Dish','やく',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (180,'泊','overnight','Water, White','と.まる; と.める',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (181,'陣','camp','Bow, Car','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (182,'慮','prudence','Tiger spots, Rice field, Heart','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (183,'弾','bullet','Bow, Rice Field, Ten','たま; はず.む; ひ.く',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (184,'勤','diligence','Flower, Power, Mouth, Soil, One','つと.まる; つと.める',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (185,'推','conjecture','Hand, Bird','お.す',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (186,'卓','eminent','Day, Ten','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (187,'誌','document','Say, Gentleman, Heart','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (188,'仙','hermit','Person, Mountain','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (189,'陸','land','Bow, Soil, Legs','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (190,'頬','cheek','Fire, Page','ほお',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (191,'拠','foothold','Hand, Late, Table','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (192,'嬢','lass','Woman, Kettle, Garment','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (193,'省','focus','Small, Eye','かえり.みる; はぶ.く',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (194,'障','hinder','Bow, Erect, Day, Ten','さわ.る',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (195,'虚','void','Tiger Spots, One','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (196,'戯','frolic','Void, Halberd','たわむ.れる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (197,'尽','exhaust','Shaku, Ice','つ.かす; つ.きる; つ.くす',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (198,'併','join','Person, Twenty','あわ.せる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (199,'惜','pity','Wand, Two, Stick, Day','お.しい; お.しむ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (200,'畳','tatami mat','Rice Field, Crown, Eye','たた.む; たたみ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (201,'姫','princess','Woman, Retainer','ひめ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (202,'検','examination','Tree, Roof, One, Mouth','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (203,'党','party','Crown, Mouth, Legs','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (204,'製','made in...','Cow, Towel, Sword, Garment','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (205,'誤','mistake','Say, Mouth, Eight','あやま.る',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (206,'呂','spine','spine','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (207,'執','tenacious','Round, Soil, Spicy','と.る',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (208,'華','splendor','Flower, Ten, Rice Field, One','はな',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (209,'袋','sack','Person, Halberd, Garment','ふくろ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (210,'減','dwindle','Water, Halberd, One, Mouth','へ.らす; へ.る',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (211,'輩','comrade','Mistake, Car','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (212,'浜','seacoast','Water, Ax, Eight','はま',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (213,'創','genesis','Roof, One, Sword, Mouth','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (214,'莫','shalt','Flower, Day, Large','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (215,'墓','grave','Large, Soil, Day, Flower','はか',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (216,'救','salvation','Strike, Water, Dot','すく.う',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (217,'模','imitation','Tree, Large, Flower, Day','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (218,'燃','burn','Fire, Dog, Evening','も.える; も.す; も.やす',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (219,'刑','punish','Twenty, Sword','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (220,'型','mould','Soil, Punish','かた',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (221,'杉','cedar','Tree, Three','すぎ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (222,'咲','blossom','Mouth, Twenty','さ.く',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (223,'昆','descendants','Day, Compare','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (224,'混','mix','Water, Descendants','ま.ざる; ま.じる; ま.ぜる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (225,'麗','lovely','Cliff, Compare, Net','うるわ.しい',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (226,'亭','pavilion','Kettle, Mouth, Crown, Pin','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (227,'侍','waiter','Person, Buddhist Temple','さむらい',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (228,'査','investigate','Tree, Ear','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (229,'震','quake','Rain, Cliff, Garment','ふる.う; ふる.える',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (230,'曜','weekday','Day, Yo, Bird','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (231,'尚','esteem','Mouth, Upside down Box','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (232,'鶴','crane','Bird, Chicken','つる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (233,'敗','failure','Shellfish, Strike','やぶ.れる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (234,'乞','beg','beg','こ.う',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (235,'迄','until','Road, Beg','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (236,'功','achievement','Construction, Power','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (237,'宜','best regards','Crown, Ear','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (238,'費','expense','Shellfish, Bow','つい.える; つい.やす',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (239,'延','prolong','Correct, Long Stride','の.ばす; の.びる; の.べる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (240,'除','exclude','Bow, Roof, Two, Small','のぞ.く',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (241,'栄','flourish','Crown, Tree','さか.える; は.え; は.える',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (242,'踊','jump','Leg, Utilize','おど.り; おど.る',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (243,'繰','winding','Thread, Goods, Tree','く.る',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (244,'貫','pierce','Rice Field, One, Shellfish','つらぬ.く',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (245,'慣','accustomed','Wand, Pierce','な.らす; な.れる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (246,'看','watch over','Eye, Hand','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (247,'賀','congratulations','Shellfish, Add(Power, Mouth)','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (248,'険','precipitous','Bow, Roof, Mouth, Person','けわ.しい',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (249,'猫','cat','Dog, Flower, Rice Field','ねこ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (250,'適','suitable','Road, Sheep, Sheep, Harden','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (251,'尼','nun','Corpse, Spoon','あま',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (252,'泥','mud','Water, Nun','どろ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (253,'録','record','Gold, Yo, Water','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (254,'歯','tooth','Stop, Rice, Upside down Box','は',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (255,'漢','Sino-','Water, Flower, Large, One, Mouth','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (256,'飾','decorate','Roof, Northeast, Towel','かざ.る',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (257,'机','desk','Tree, Table','つくえ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (258,'椅','chair','Tree, Large, Mouth','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (259,'冒','risk','Day, Eye','おか.す',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (260,'帽','cap','Towel, Risk','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (261,'載','load','Car, Halberd, Soil','の.せる; の.る',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (262,'俳','haiku','Person, Mistake','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (263,'設','establishment','Say, Pike','もう.ける',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (264,'帳','notebook','Towel, Long(Yo, Garment)','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (265,'浴','bathe','Water, Roof, Mouth','あ.びせる; あ.びる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (266,'吐','spit','Mouth, Soil','は.く',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (267,'瀬','rapids','Water, Page, Tree, Mouth','せ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (268,'慢','ridicule','Wand, Day, Net, Or again','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (269,'宝','treasure','Crown, Jewel','たから',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (270,'竜','dragon','Erect, Rice Field','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (271,'扉','front door','Door, Mistake','とびら',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (272,'拝','worship','Hand, One, King','おが.む',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (273,'簡','simplicity','Gates, Day','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (274,'菊','chrysanthemum','Flower, Wrap, Rice','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (275,'愚','foolish','Day, Crown, Private, Heart','おろ.か',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (276,'律','rhythm','Stop, Brush','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (277,'革','leather','leather','かわ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (278,'編','compilation','Thread, Door, Tome','あ.む',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (279,'勘','intuition','Ear, Legs, Power','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (280,'規','standard','See, Two, Large','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (281,'司','director','One, Feather, One, Mouth','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (282,'釈','explanation','Shaku, Rice, One','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (283,'弥','more and more','Bow, Small','や',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (284,'童','juvenile','Erect, Ri','わらべ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (285,'袖','sleeve','Clothes, Rice Field','そで',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (286,'揚','hoist','Hands, Day, Pig','あ.がる; あ.げる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (287,'于','Going','Going','ここに',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (288,'宇','eaves','Crown, Going','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (289,'換','interchange','Hand, Wrap, Legs, Large','か.える; か.わる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (290,'材','lumber','Tree, One, Slash, Feather','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (291,'悟','enlightenment','Wand, Five, Mouth','さと.る',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (292,'努','toil','Woman, Or again, Power','つと.める',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (293,'廊','corridor','Cliff, Northeast, Bow','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (294,'維','fiber','Thread, Bird','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (295,'羅','gauze','Net, Thread, Bird','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (296,'盗','steal','Water, Lack, Dish','ぬす.む',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (297,'覧','perusal','Retainer, One, SEe','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (298,'輝','radiance','Rice, Crown, car','かがや.く',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (299,'球','ball','King, Water, One','たま',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (300,'添','annexed','Large, Water, One','そ.う; そ.える',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (301,'闘','fight','Gates, Measurement, Mouth','たたか.う',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (302,'烈','ardent','Death, Sword, Fire','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (303,'畑','farm','Fire, Rice Field','はた; はたけ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (304,'詞','parts of speech','Say, One, Mouth','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (305,'蘭','orchid','Flower, Gates, Tree, Rice Field','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (306,'嬉','overjoyed','Woman, Gentleman, Mouth','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (307,'収','income','Or Again','おさ.まる; おさ.める',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (308,'乳','milk','Child, Second','ち; ちち',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (309,'柱','pillar','Tree, King','はしら',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (310,'摩','chafe','Cliff, Tree, Hand','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (311,'覗','peek','One, Mouth, See','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (312,'釣','angling','Gold, Ladle','つ.る',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (313,'導','guidance','Road, Measurement, Neck','みちび.く',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (314,'濃','concentrated','Water, Rice Field, Cliff, One, Garment','こ.い',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (315,'算','calculate','Bamboo, World','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (316,'含','include','Roof, One, Mouth','ふく.む; ふく.める',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (317,'襲','attack','Erect, Flesh, Retainer, Garment','おそ.う',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (318,'旗','national flag','Direction, Ear','はた',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (319,'熊','bear','Private, Flesh, Spoon, Fire','くま',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (320,'嫁','marry into','Woman, Crown, Pig','とつ.ぐ; よめ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (321,'策','scheme','Bamboo, Towel','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (322,'圧','pressure','Cliff, Soil','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (323,'寧','rather','Crown, Heart, Net','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (324,'専','specialty','Rice Field, Ten, Measurement','もっぱ.ら',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (325,'財','property','Shellfish, One, Slash','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (326,'揺','swing','Hand, Mountain, Dry','ゆ.さぶる; ゆ.すぶる; ゆ.する; ゆ.らぐ; ゆ.る; ゆ.るぐ; ゆ.れる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (327,'鮮','fresh','Wrap, Rice Field, Fire, Sheep','あざ.やか',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (328,'防','ward off','Bow, Direction','ふせ.ぐ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (329,'偶','accidentally','Person, Rice Field','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (330,'庵','hermitage','Cliff, Large, Rice Field','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (331,'築','fabricate','Bamboo, Construction, Tree, Table','きず.く',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (332,'誘','entice','Say, Tree, From','さそ.う',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (333,'希','hope','Slash, Large, Towel','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (334,'垂','droop','One, Stick, Slash','た.らす; た.れる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (335,'阪','Heights','Bow, Cliff, Or Again','さか',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (336,'停','halt','Person, Kettle, Mouth, Crown, Street','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (337,'孫','grandchild','Child, Thread','まご',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (338,'鉢','bowl','Gold, Book','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (339,'潮','tide','Water, Flesh, Ten, Day','しお',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (340,'操','maneuver','Hand, Goods, Tree','あやつ.る; みさお',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (341,'免','excuse','Mouth, Legs, Wrap','まぬか.れる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (342,'隶','Extend','Stick, Yo, Water','タイ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (343,'康','sane','Cliff, Yo, Water','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (344,'唐','T''ang','Cliff, Yo, Mouth','から',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (345,'針','needle','Gold, Ten','はり',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (346,'乏','destitution','Slash, The Later','とぼ.しい',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (347,'略','abbreviation','Rice Field, Late, Mouth','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (348,'枕','pillow','Tree, Crown, Legs','まくら',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (349,'蛇','snake','Insect, Crown, SPoon','へび',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (350,'裕','abundant','Clothes, Roof, Mouth','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (351,'紫','purple','Stop, Spoon, Thread','むらさき',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (352,'序','preface','Cliff, Private, Street','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (353,'獄','prison','Dog, Say, Dog','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (354,'練','practice','Thread, Rice Field, Tree','ね.る',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (355,'抵','resist','Hand, Clan','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (356,'遅','slow','Road, Corpse, Sheep','おく.らす; おく.れる; おそ.い',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (357,'避','evade','Road, Corpse, Mouth, Erect, Ten','さ.ける',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (358,'癖','mannerism','Cliff, Corpse, Mouth, Erect, Ten','くせ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (359,'幼','infancy','Short thread, Power','おさな.い',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (360,'澄','lucidity','Water, Cliff, One, Mouth','す.ます; す.む',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (361,'駆','drive','Horse, Slash, Box on side','か.ける; か.る',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (362,'只','only','Mouth, Eight','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (363,'扱','handle','Hand, Reach out','あつか.う',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (364,'緑','green','Thread, Yo, Water','みどり',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (365,'敏','cleverness','Mother, Strike','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (366,'繁','luxuriant','Cleverness, thread','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (367,'隆','hump','Bow, Strike, Life','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (368,'巧','adroit','Construction','たく.み',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (369,'誠','sincerity','Say, Halberd','まこと',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (370,'狭','cramped','Dog, Large, Kettle','せば.まる; せば.める; せま.い',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (371,'遇','interview','Road, Rice Field','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (372,'蒼','pale blue','Flower, Roof, Mouth','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (373,'厚','thick','Cliff, day, Child','あつ.い',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (374,'綱','hawser','Thread, Mountain, Upside Down Box','つな',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (375,'鋭','pointed','Gold, Mouth, Legs','するど.い',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (376,'透','transparent','Road, Tree, From','す.かす; す.く; す.ける',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (377,'噂','gossip','Mouth, West, Measurement','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (378,'替','exchange','Not Yet, Day','か.える; か.わる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (379,'潜','submerge','Water, Exchange','ひそ.む; もぐ.る',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (380,'封','seal','Soil, Measurement','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (381,'愉','pleasure','Water, Roof, One, Flesh, Sword','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (382,'牧','breed','Cow, Strike','まき',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (383,'巛','River','River','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (384,'巡','patrol','Road, River','めぐ.る',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (385,'票','ballot','One, Two, Small','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (386,'標','signpost','Tree, Ballot','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (387,'嘘','fib','Mouth, Cliff, Divining','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (388,'裁','tailor','Soil, Halberd, Garment','さば.く; た.つ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (389,'壇','podium','Soil, Kettle, Mouth, day, One','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (390,'靴','shoes','Compare, Twenty, Ten','くつ',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (391,'授','impart','Hand, Or Again, Crown','さず.かる; さず.ける',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (392,'典','code','Legs, Twenty, Mouth','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (393,'幽','faint','Mountain, Short Thread','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (394,'唇','lips','Cliff, One, Garment, Mouth','くちびる',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (395,'茂','overgrown','Flower, Halberd','しげ.る',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (396,'届','deliver','COrpse, Rice Field','とど.く; とど.ける',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (397,'戒','commandment','Halberd, Twenty','いまし.める',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (398,'械','contraption','Tree, Commandment','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (399,'奪','rob','Large, Bird, Measurement','うば.う',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (400,'拾','pick up','Hand, Roof, One, Mouth','ひろ.う',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Gold` VALUES (401,'属','belong','Corpse, Name of Chinese Emperor','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
COMMIT;
